name: CI

on:
  workflow_dispatch:
    inputs:
      chosen-runner:
        description: 'Choose the runner to use for the workflow'
        required: true
        type: choice
        options:
        - self-ubuntu-24.04
        - ubuntu-24.04
        default: self-ubuntu-24.04
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-runner:
    runs-on: ubuntu-24.04
    outputs:
      runner-available: ${{ steps.check.outputs.runner_available }}
    env: 
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check for self-ubuntu-24.04 runner at repository level
        id: check
        run: |
          gh --version
          RUNNERS_COUNT=$(gh api repos/${{ github.repository_owner }}/actions/runners --jq '.runners | map(select(.labels[].name=="self-ubuntu-24.04")) | length')
          echo "Found ${RUNNERS_COUNT} self-ubuntu-24.04 runner(s)"
          if [ "$RUNNERS_COUNT" -gt 0 ]; then
            echo "runner_available=true" >> $GITHUB_OUTPUT
          else
            echo "runner_available=false" >> $GITHUB_OUTPUT
          fi
  build-cache:
    if: 0
    runs-on: self-ubuntu-24.04
    permissions:
      packages: write
    continue-on-error: false
    strategy:
      matrix:
        env_variant: [omp]
    steps:
   
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Spack
      uses: spack/setup-spack@v2.1.1
      with:
        buildcache: true
        color: true
        path: _spack
    - name: Install
      run: |
        ls -l
        spack -e spack/kokkidio-${{ matrix.env_variant }} install --no-check-signature --use-buildcache auto

    - name: Push packages and update index
      run: |
        spack -e spack/kokkidio-${{ matrix.env_variant }} mirror set --push --oci-username ${{ github.actor }} --oci-password "${{ secrets.GITHUB_TOKEN }}" numpex-buildcache
        spack -e spack/kokkidio-${{ matrix.env_variant }} buildcache push --base-image ubuntu:24.04 --unsigned --update-index numpex-buildcache
      if: ${{ !cancelled() }}

  build:
    needs: build-cache
    runs-on: ${{ github.event.inputs.chosen-runner || 'ubuntu-24.04' }}
    permissions:
      packages: write
    continue-on-error: true
    strategy:
      matrix:
        env_variant: [omp]
        preset: [default]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Spack
      uses: spack/setup-spack@v2.1.1
      with:
        buildcache: true
        color: true
        path: _spack

    - name: Spack Install
      run: spack -e spack/kokkidio-${{ matrix.env_variant }} install --no-check-signature --use-buildcache auto

    - name: Configure CMake
      shell: spack-bash {0}
      run: |
        spack env activate spack/kokkidio-${{ matrix.env_variant }}
        cmake --preset ${{ matrix.preset }}

    - name: Build
      run: cmake --build --preset ${{ matrix.preset }}

    - name: Test
      run: ctest --preset ${{ matrix.preset }}
