name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-cache:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    continue-on-error: false
    strategy:
      matrix:
        env_variant: [omp]
    steps:
   
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Spack
      uses: spack/setup-spack@v2.1.1
      with:
        buildcache: true
        color: true
        path: _spack
    - name: Install
      run: |
        ls -l
        spack -e spack/kokkidio-${{ matrix.env_variant }} install --no-check-signature --use-buildcache auto

    - name: Push packages and update index
      run: |
        spack -e spack/kokkidio-${{ matrix.env_variant }} mirror set --push --oci-username ${{ github.actor }} --oci-password "${{ secrets.GITHUB_TOKEN }}" numpex-buildcache
        spack -e spack/kokkidio-${{ matrix.env_variant }} buildcache push --base-image ubuntu:24.04 --unsigned --update-index numpex-buildcache
      if: ${{ !cancelled() }}

  build:
    needs: build-cache
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    continue-on-error: true
    strategy:
      matrix:
        env_variant: [omp]
        preset: [default, kokkos]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Spack
      uses: spack/setup-spack@v2.1.1
      with:
        buildcache: true
        color: true
        path: _spack

    - name: Spack Install
      run: spack -e spack/kokkidio-${{ matrix.env_variant }} install --no-check-signature --use-buildcache auto

    - name: Configure CMake
      shell: spack-bash {0}
      run: |
        spack env activate spack/kokkidio-${{ matrix.env_variant }}
        cmake --preset ${{ matrix.preset }}

    - name: Build
      run: cmake --build --preset ${{ matrix.preset }}

    - name: Test
      run: ctest --preset ${{ matrix.preset }}
